#!/usr/bin/env bash
#
# ICMS server installer.
#
#   ./install.sh                 install / upgrade and start the stack
#   ./install.sh --migrate-from-postgres postgresql://user:pass@host:5432/icms
#                                also copy existing PostgreSQL data into MariaDB
#   ./install.sh --port 9000     publish the app on a different host port
#
# Creates .env with generated secrets on first run and never overwrites it.

set -euo pipefail

cd "$(dirname "$0")"

ENV_FILE=".env"
APP_PORT="${APP_PORT:-8080}"
PG_URL=""

# ─── args ────────────────────────────────────────────────────────────────────
while [ $# -gt 0 ]; do
  case "$1" in
    --migrate-from-postgres) PG_URL="${2:-}"; shift 2 ;;
    --port)                  APP_PORT="${2:-8080}"; shift 2 ;;
    -h|--help)               sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

say()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m warn\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m!!!\033[0m %s\n' "$*" >&2; exit 1; }

# ─── prerequisites ───────────────────────────────────────────────────────────
say "Checking prerequisites"

command -v docker >/dev/null 2>&1 || die \
  "Docker is not installed. Install it first:  curl -fsSL https://get.docker.com | sh"

if docker compose version >/dev/null 2>&1; then
  DC="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  DC="docker-compose"
else
  die "Docker Compose is not available. Install the docker-compose-plugin package."
fi

docker info >/dev/null 2>&1 || die \
  "Cannot talk to the Docker daemon. Start it (systemctl start docker), or add yourself to the docker group and log back in."

say "Docker OK ($($DC version --short 2>/dev/null || echo compose))"

# ─── secrets / .env ──────────────────────────────────────────────────────────
gen() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "${1:-40}"; }

if [ -f "$ENV_FILE" ]; then
  say "Reusing existing $ENV_FILE (delete it to regenerate secrets)"
else
  say "Generating $ENV_FILE with fresh secrets"
  cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# Keep this file private and out of version control.

DB_NAME=icms
DB_USER=icms_user
DB_PASSWORD=$(gen 32)
DB_ROOT_PASSWORD=$(gen 32)

# Signs login tokens. Changing it logs everyone out.
JWT_SECRET=$(gen 48)

# Host port the web UI is published on.
APP_PORT=$APP_PORT

# Only needed if the SPA is served from a different origin than the API.
CORS_ORIGINS=

# The app sits behind the compose network; keep this on so client IPs are
# read from X-Forwarded-For for login rate limiting.
TRUST_PROXY=true
EOF
  chmod 600 "$ENV_FILE"
fi

# Honour --port even when .env already exists. Edited in place rather than via
# sed -i.bak, which would leave a world-readable copy of the secrets on disk.
if grep -q '^APP_PORT=' "$ENV_FILE"; then
  tmp=$(mktemp) && chmod 600 "$tmp"
  sed "s/^APP_PORT=.*/APP_PORT=$APP_PORT/" "$ENV_FILE" > "$tmp"
  cat "$tmp" > "$ENV_FILE"   # preserves the original file's 600 permissions
  rm -f "$tmp"
else
  echo "APP_PORT=$APP_PORT" >> "$ENV_FILE"
fi
chmod 600 "$ENV_FILE"

# ─── build & start ───────────────────────────────────────────────────────────
say "Building the application image (first run takes a few minutes)"
$DC build

say "Starting MariaDB and the application"
$DC up -d

# ─── wait for health ─────────────────────────────────────────────────────────
say "Waiting for the application to report healthy"
ok=false
for _ in $(seq 1 60); do
  if curl -fsS "http://127.0.0.1:${APP_PORT}/api/health" >/dev/null 2>&1; then
    ok=true; break
  fi
  sleep 3
done

if [ "$ok" != true ]; then
  warn "The app did not become healthy in time. Recent logs:"
  $DC logs --tail=60 app
  die "Install incomplete. Fix the errors above and re-run ./install.sh"
fi

say "Application is healthy"

# ─── optional data migration ─────────────────────────────────────────────────
if [ -n "$PG_URL" ]; then
  say "Migrating data from PostgreSQL into MariaDB"
  # Runs inside the app container so it reaches MariaDB over the compose network.
  $DC exec -T -e "PG_URL=$PG_URL" app node migrate-to-mariadb.js \
    || die "Data migration failed — the app is running but the old data was not copied."
  say "Data migration finished"
fi

# ─── done ────────────────────────────────────────────────────────────────────
IP=$(hostname -I 2>/dev/null | awk '{print $1}')
cat <<EOF

──────────────────────────────────────────────────────────────
 ICMS is running.

   Local:    http://localhost:${APP_PORT}
   Network:  http://${IP:-<server-ip>}:${APP_PORT}

 First sign-in:  owner@icms.com / owner123
 CHANGE THAT PASSWORD IMMEDIATELY under Settings → Users.

 Useful commands:
   $DC logs -f app        follow application logs
   $DC ps                 container status
   $DC restart app        restart the API
   $DC down               stop everything (data is kept in volumes)
   ./backup.sh            dump the database

 Secrets are in .env (mode 600). Back it up somewhere safe —
 losing JWT_SECRET logs everyone out; losing DB_PASSWORD locks
 you out of the database.
──────────────────────────────────────────────────────────────
EOF
