#!/usr/bin/env bash
#
# ICMS installer for a server without Docker.
#
# Installs against a system MariaDB and runs the API under PM2, serving the
# built frontend from the same origin (so no CORS configuration is needed).
#
#   ./install-native.sh                    install / upgrade and start
#   ./install-native.sh --port 3456        listen on a different port
#   ./install-native.sh --db-root-user x   MariaDB admin user for the one-time
#                                          database + user creation
#   ./install-native.sh --skip-build       reuse the existing frontend build
#   ./install-native.sh --migrate-from-postgres postgresql://u:p@host:5432/icms
#
# Configuration is written to icms-backend/.env (mode 600) and never
# overwritten: an existing JWT_SECRET and DB_PASSWORD are preserved, so
# re-running does not log everyone out or lock you out of the database.

set -euo pipefail
cd "$(dirname "$0")"

APP_NAME="icms"
APP_PORT="3001"
DB_NAME="icms"
DB_USER="icms_user"
DB_HOST="127.0.0.1"
DB_PORT="3306"
DB_ROOT_USER=""
SKIP_BUILD=false
PG_URL=""
ENV_FILE="icms-backend/.env"

say()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarn\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m!!!\033[0m %s\n' "$*" >&2; exit 1; }

while [ $# -gt 0 ]; do
  case "$1" in
    --port)         APP_PORT="${2:?}"; shift 2 ;;
    --db-name)      DB_NAME="${2:?}"; shift 2 ;;
    --db-user)      DB_USER="${2:?}"; shift 2 ;;
    --db-host)      DB_HOST="${2:?}"; shift 2 ;;
    --db-port)      DB_PORT="${2:?}"; shift 2 ;;
    --db-root-user) DB_ROOT_USER="${2:?}"; shift 2 ;;
    --skip-build)   SKIP_BUILD=true; shift ;;
    --migrate-from-postgres) PG_URL="${2:?}"; shift 2 ;;
    -h|--help)      sed -n '2,18p' "$0"; exit 0 ;;
    *) die "Unknown option: $1" ;;
  esac
done

# ─── prerequisites ───────────────────────────────────────────────────────────
say "Checking prerequisites"

command -v node >/dev/null 2>&1 || die "Node.js is not installed."
NODE_MAJOR=$(node -p 'process.versions.node.split(".")[0]')
[ "$NODE_MAJOR" -ge 20 ] || die "Node.js 20 or newer is required (found $(node -v))."
say "Node.js OK ($(node -v))"

command -v npm >/dev/null 2>&1 || die "npm is not installed."

# The mariadb CLI is needed to create the database and apply the schema.
if command -v mariadb >/dev/null 2>&1; then
  MYSQL_CLI=mariadb
elif command -v mysql >/dev/null 2>&1; then
  MYSQL_CLI=mysql
else
  die "No mariadb/mysql client found. Install the server and client:
     sudo apt update && sudo apt install -y mariadb-server mariadb-client"
fi
say "MariaDB client OK ($MYSQL_CLI)"

command -v pm2 >/dev/null 2>&1 || die "PM2 is not installed:  npm install -g pm2"
say "PM2 OK ($(pm2 -v 2>/dev/null | tail -1))"

command -v curl >/dev/null 2>&1 || die "curl is not installed."

# ─── secrets / env ───────────────────────────────────────────────────────────
gen() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "${1:-40}"; }

# Reuse existing values so re-running is non-destructive.
prev() {
  [ -f "$ENV_FILE" ] || return 0
  sed -n "s/^$1=//p" "$ENV_FILE" | tail -1
}

JWT_SECRET="$(prev JWT_SECRET)"; [ -n "$JWT_SECRET" ] || JWT_SECRET="$(gen 48)"
DB_PASSWORD="$(prev DB_PASSWORD)"; [ -n "$DB_PASSWORD" ] || DB_PASSWORD="$(gen 32)"

if [ -f "$ENV_FILE" ]; then
  BACKUP="$ENV_FILE.bak-$(date -u '+%Y%m%d-%H%M%S')"
  # Created with restrictive permissions before any secret is written into it.
  (umask 077; cp "$ENV_FILE" "$BACKUP")
  say "Existing config backed up to $BACKUP (secrets preserved)"
fi

say "Writing $ENV_FILE"
(
  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by install-native.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# Keep this file private. It is gitignored.

NODE_ENV=production
PORT=$APP_PORT

DB_CLIENT=mysql
DB_HOST=$DB_HOST
DB_PORT=$DB_PORT
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD

# Signs login tokens. Changing it logs everyone out.
JWT_SECRET=$JWT_SECRET

# The API serves the built frontend, so requests are same-origin and this can
# stay empty. Set it only if the UI is hosted elsewhere.
CORS_ORIGINS=

# Read client IPs from X-Forwarded-For when behind nginx, so the login rate
# limiter buckets per user rather than per proxy.
TRUST_PROXY=true

UPLOAD_DIR=./uploads

# Local AI (agent + OCR field extraction). Leave as-is if Ollama runs on this
# host; the app also accepts a value saved in Settings -> AI.
OLLAMA_URL=http://127.0.0.1:11434
EOF
)
chmod 600 "$ENV_FILE"

# ─── database ────────────────────────────────────────────────────────────────
say "Preparing the database"

app_can_connect() {
  MYSQL_PWD="$DB_PASSWORD" "$MYSQL_CLI" -h "$DB_HOST" -P "$DB_PORT" \
    -u "$DB_USER" "$DB_NAME" -e "SELECT 1" >/dev/null 2>&1
}

if app_can_connect; then
  say "Application database user already works"
else
  say "Creating database and user (needs MariaDB admin access)"
  SQL="CREATE DATABASE IF NOT EXISTS \`$DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';
CREATE USER IF NOT EXISTS '$DB_USER'@'$DB_HOST' IDENTIFIED BY '$DB_PASSWORD';
ALTER USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';
ALTER USER '$DB_USER'@'$DB_HOST' IDENTIFIED BY '$DB_PASSWORD';
GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'localhost';
GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'$DB_HOST';
FLUSH PRIVILEGES;"

  done_setup=false
  # A fresh Debian/Ubuntu MariaDB authenticates root over the unix socket.
  if [ -n "$DB_ROOT_USER" ]; then
    if "$MYSQL_CLI" -u "$DB_ROOT_USER" -p -e "$SQL" 2>/dev/null; then done_setup=true; fi
  elif sudo -n true 2>/dev/null && sudo "$MYSQL_CLI" -e "SELECT 1" >/dev/null 2>&1; then
    sudo "$MYSQL_CLI" -e "$SQL" && done_setup=true
  elif "$MYSQL_CLI" -u root -e "SELECT 1" >/dev/null 2>&1; then
    "$MYSQL_CLI" -u root -e "$SQL" && done_setup=true
  fi

  if [ "$done_setup" != true ]; then
    cat <<EOF

Could not create the database automatically. Run this once as a MariaDB admin,
then re-run this script:

  sudo $MYSQL_CLI <<'SQL'
$SQL
SQL

EOF
    die "Database not provisioned."
  fi
  app_can_connect || die "Created the user but still cannot connect as $DB_USER."
  say "Database and user ready"
fi

say "Applying schema (idempotent)"
# --force matters: MariaDB has no CREATE INDEX IF NOT EXISTS before 10.6, so a
# re-run hits "Duplicate key name" and without --force the client would abort
# and skip every statement after it, including the ALTERs and seed rows.
MYSQL_PWD="$DB_PASSWORD" "$MYSQL_CLI" --force \
  -h "$DB_HOST" -P "$DB_PORT" -u "$DB_USER" "$DB_NAME" \
  < icms-backend/schema.mariadb.sql 2>&1 | grep -viE "duplicate key name|insecure" || true
say "Schema applied"

# ─── dependencies and build ──────────────────────────────────────────────────
say "Installing API dependencies"
( cd icms-backend && npm ci --omit=dev --no-audit --fund=false )

if [ "$SKIP_BUILD" = true ]; then
  warn "Skipping frontend build (--skip-build)"
else
  say "Building the frontend"
  # devDependencies are required here: vite is a build-time tool.
  ( cd icms-frontend && npm ci --no-audit --fund=false && VITE_API_URL="" npm run build )
  say "Publishing the build for the API to serve"
  rm -rf icms-backend/public
  cp -r icms-frontend/dist icms-backend/public
fi

mkdir -p icms-backend/uploads

# ─── optional data migration ─────────────────────────────────────────────────
if [ -n "$PG_URL" ]; then
  say "Migrating data from PostgreSQL"
  ( cd icms-backend && PG_URL="$PG_URL" node migrate-to-mariadb.js ) \
    || die "Data migration failed. The schema is in place but the old data was not copied."
fi

# ─── run under PM2 ───────────────────────────────────────────────────────────
say "Starting the application"

# Run node directly rather than through npm: an npm wrapper makes PM2 supervise
# the wrapper instead of the server, so restarts and signals do not reach it.
# delete-then-start keeps exactly one app; the previous script left a new
# stopped/errored entry behind on every run.
pm2 delete "$APP_NAME" >/dev/null 2>&1 || true
pm2 start src/index.js \
  --name "$APP_NAME" \
  --cwd "$PWD/icms-backend" \
  --time \
  --max-memory-restart 400M \
  >/dev/null
pm2 save >/dev/null 2>&1 || true

# ─── wait for health ─────────────────────────────────────────────────────────
say "Waiting for the application to report healthy"
HEALTHY=false
for _ in $(seq 1 45); do
  if curl -fsS "http://127.0.0.1:${APP_PORT}/api/health" >/dev/null 2>&1; then
    HEALTHY=true; break
  fi
  sleep 2
done

if [ "$HEALTHY" != true ]; then
  warn "Did not become healthy within 90s. Recent logs:"
  echo
  pm2 logs "$APP_NAME" --lines 40 --nostream || true
  echo
  die "Install incomplete. Fix the errors above and re-run ./install-native.sh"
fi

say "Application is healthy"
curl -fsS "http://127.0.0.1:${APP_PORT}/api/health"; echo

IP=$(hostname -I 2>/dev/null | awk '{print $1}')
cat <<EOF

──────────────────────────────────────────────────────────────
 ICMS is running (no Docker).

   Local:    http://localhost:${APP_PORT}
   Network:  http://${IP:-<server-ip>}:${APP_PORT}

 First sign-in:  owner@icms.com / owner123
 CHANGE THAT PASSWORD IMMEDIATELY under Settings -> Users.

 Useful commands:
   pm2 logs ${APP_NAME}          follow application logs
   pm2 restart ${APP_NAME}       restart the API
   pm2 status                    process status
   pm2 monit                     live resource view
   ./backup-native.sh            dump database + uploads

 Start on boot (run once, follow the command it prints):
   pm2 startup

 Secrets live in ${ENV_FILE} (mode 600). Back it up somewhere safe:
 losing JWT_SECRET logs everyone out, losing DB_PASSWORD locks you
 out of the database.
──────────────────────────────────────────────────────────────
EOF
